# Generated by Django 2.0.9 on 2018-12-10 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='due',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='todoitem',
            name='start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
