# Generated by Django 2.0.9 on 2019-02-23 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_auto_20190223_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='time_estimate',
            field=models.CharField(blank=True, choices=[('5m', '5m'), ('15m', '15m'), ('30m', '30m'), ('1h', '1h'), ('4h', '4h'), ('1d', '1d'), ('3d', '3d'), ('1w', '1w'), ('5w', '5w'), ('10w', '10w'), ('20w', '20w')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='todoitem',
            name='urgency',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
    ]
