# Generated by Django 2.0.9 on 2019-02-23 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_auto_20190223_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='members', to='todo.TodoItem'),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='dependencies',
            field=models.ManyToManyField(blank=True, related_name='dependents', to='todo.TodoItem'),
        ),
    ]
