# Generated by Django 2.0.9 on 2019-03-14 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0008_auto_20190223_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='streak',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
