# Generated by Django 2.0.9 on 2019-04-05 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0010_todoitem_calculate_streak'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='order',
            field=models.FloatField(),
        ),
    ]
