# Generated by Django 2.0.9 on 2019-09-27 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0011_auto_20190405_0834'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
