# Generated by Django 2.0.9 on 2019-10-01 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0013_todoitem_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='snooze_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
