# Generated by Django 3.0.5 on 2020-06-29 13:24

import django.contrib.postgres.fields
from django.db import migrations, models
import model_utils.fields


class Migration(migrations.Migration):

    replaces = [('todo', '0015_todoitem_status_history'), ('todo', '0016_auto_20200629_1244'), ('todo', '0017_todoitem_status_history_start'), ('todo', '0018_auto_20200629_1253'), ('todo', '0019_auto_20200629_1303'), ('todo', '0020_auto_20200629_1309')]

    dependencies = [
        ('todo', '0014_todoitem_snooze_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='status_history',
            field=django.contrib.postgres.fields.ArrayField(base_field=model_utils.fields.StatusField(max_length=100, no_check_for_status=True), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='todoitem',
            name='status_history_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
