# Generated by Django 2.0.9 on 2019-09-29 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='togglApiToken',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
