# Generated by Django 3.0.5 on 2020-05-26 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190930_0255'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='goals',
            field=models.TextField(blank=True, null=True),
        ),
    ]
